version: '3.4'

services:
  aggrid:
    image: aggrid
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3001"
    networks:
      - aggrid-network

  aggrid-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
      - ./ssl/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
      - ./ssl/dhparam.pem:/etc/nginx/dhparam.pem:ro
    depends_on:
      - aggrid
    ports:
      - "9000:80"
      - "4430:443"  
    networks:
      - aggrid-network

networks:
  aggrid-network:
